name: Step 5, Trigger the workflow

# This step triggers after "My Starter Workflow" completes a run.
# This workflow updates from step 5 to step X.

# This will run every time we finish running "My Starter Workflow".
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - My Starter Workflow
    types:
      - completed

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_trigger:
    name: On trigger
    runs-on: ubuntu-latest

    steps:
      # In README.md, switch step 5 for step X.
      - name: Update to step X
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: X
